[project]
name = "math-project"
version = "0.1.0"
description = "Math project"
readme = "README.md"
authors = [
    { name = "Éderson Ferreira", email = "380843+edersonmf@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "keras>=3.11.3",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "scikit-learn>=1.7.2",
    "tensorflow>=2.21.0",
]
